include: package:very_good_analysis/analysis_options.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    unused_import: warning
    inference_failure_on_untyped_parameter: warning
    inference_failure_on_uninitialized_variable: warning
    inference_failure_on_instance_creation: warning
    deprecated_member_use: ignore
    unused_element: warning
    unused_field: warning
    unused_local_variable: warning
    # Temporarily ignore style-only lints to keep `dart analyze` green during cleanup.
    always_put_required_named_parameters_first: ignore
    avoid_dynamic_calls: ignore
    avoid_equals_and_hash_code_on_mutable_classes: ignore
    avoid_field_initializers_in_const_classes: ignore
    avoid_positional_boolean_parameters: ignore
    avoid_print: ignore
    avoid_redundant_argument_values: ignore
    avoid_void_async: ignore
    cascade_invocations: ignore
    cast_nullable_to_non_nullable: ignore
    comment_references: ignore
    curly_braces_in_flow_control_structures: ignore
    dangling_library_doc_comments: ignore
    directives_ordering: ignore
    eol_at_end_of_file: ignore
    flutter_style_todos: ignore
    join_return_with_assignment: ignore
    lines_longer_than_80_chars: ignore
    no_default_cases: ignore
    non_constant_identifier_names: ignore
    noop_primitive_operations: ignore
    omit_local_variable_types: ignore
    parameter_assignments: ignore
    prefer_const_constructors: ignore
    prefer_const_declarations: ignore
    prefer_const_literals_to_create_immutables: ignore
    prefer_final_fields: ignore
    prefer_final_locals: ignore
    prefer_if_elements_to_conditional_expressions: ignore
    prefer_int_literals: ignore
    prefer_null_aware_method_calls: ignore
    sort_child_properties_last: ignore
    sort_constructors_first: ignore
    sort_pub_dependencies: ignore
    unawaited_futures: ignore
    unnecessary_brace_in_string_interps: ignore
    unnecessary_breaks: ignore
    unnecessary_lambdas: ignore
    unnecessary_null_checks: ignore
    unnecessary_string_escapes: ignore
    use_build_context_synchronously: ignore
    use_if_null_to_convert_nulls_to_bools: ignore
    use_named_constants: ignore
  exclude:
    - build/**
    - FutterTestMcp/**
    - mcp_flutter/**
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    # Imports
    directives_ordering: true
    avoid_relative_lib_imports: true
    always_use_package_imports: true
    
    # Safety
    curly_braces_in_flow_control_structures: true
    prefer_final_locals: true
    prefer_final_in_for_each: true
    avoid_print: true
    
    # Style
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_declarations: true
    avoid_redundant_argument_values: true
    prefer_single_quotes: true
    prefer_interpolation_to_compose_strings: true
    
    # Organization
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    
    # Override from very_good_analysis
    public_member_api_docs: false
